# Generated by Django 2.1.7 on 2019-09-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='coverimg',
        ),
    ]
