# Generated by Django 2.1.7 on 2019-09-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventform', '0002_remove_events_coverimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='maxcount',
            new_name='Amount',
        ),
    ]
